CREATE OR REPLACE DATABASE CALIFORNIA_COVID_ANALYTICS;
USE CALIFORNIA_COVID_ANALYTICS;

CREATE OR REPLACE SCHEMA CALIFORNIA_COVID_ANALYTICS.RAW;
CREATE OR REPLACE SCHEMA CALIFORNIA_COVID_ANALYTICS.ANALYTICS;

CREATE OR REPLACE TABLE CALIFORNIA_COVID_ANALYTICS.RAW.CA_COUNTY_DEMOGRAPHICS_2020 (
    FIPS STRING,
    COUNTY_NAME STRING PRIMARY KEY,
    POPULATION INT,
    W_POPULATION INT,
    B_POPULATION INT,
    O_POPULATION INT,
    NH_POPULATION INT,
    HI_POPULATION INT,
    NA_POPULATION INT,
    MALE_POPULATION INT,
    FEMALE_POPULATION INT,
    AGE_0_19_POPULATION INT,
    AGE_20_49_POPULATION INT,
    AGE_50_64_POPULATION INT,
    AGE_65_PLUS_POPULATION INT,
    W_POPULATION_RATIO FLOAT,
    B_POPULATION_RATIO FLOAT,
    O_POPULATION_RATIO FLOAT,
    NH_POPULATION_RATIO FLOAT,
    HI_POPULATION_RATIO FLOAT,
    NA_POPULATION_RATIO FLOAT,
    MALE_POPULATION_RATIO FLOAT,
    FEMALE_POPULATION_RATIO FLOAT,
    AGE_0_19_POPULATION_RATIO FLOAT,
    AGE_20_49_POPULATION_RATIO FLOAT,
    AGE_50_64_POPULATION_RATIO FLOAT,
    AGE_65_PLUS_POPULATION_RATIO FLOAT
);

CREATE OR REPLACE VIEW CALIFORNIA_COVID_ANALYTICS.ANALYTICS.CA_CASES_DEMOGRAPHICS_VIEW AS 
SELECT
    C.DATE,
    C.AREA,
    C.POPULATION,
    C.CASES,
    C.CUMULATIVE_CASES,
    C.DEATHS,
    C.CUMULATIVE_DEATHS,
    C.TOTAL_TESTS,
    C.CUMULATIVE_TOTAL_TESTS,
    D.MALE_POPULATION_RATIO AS MALE_POPULATION_RATIO,
    D.FEMALE_POPULATION_RATIO AS FEMALE_POPULATION_RATIO,
    D.W_POPULATION_RATIO AS W_POPULATION_RATIO,
    D.B_POPULATION_RATIO AS B_POPULATION_RATIO,
    D.O_POPULATION_RATIO AS O_POPULATION_RATIO,
    D.NH_POPULATION_RATIO AS NH_POPULATION_RATIO,
    D.HI_POPULATION_RATIO AS HI_POPULATION_RATIO,
    D.NA_POPULATION_RATIO AS NA_POPULATION_RATIO,
    D.AGE_0_19_POPULATION_RATIO AS AGE_0_19_POPULATION_RATIO,
    D.AGE_20_49_POPULATION_RATIO AS AGE_20_49_POPULATION_RATIO,
    D.AGE_50_64_POPULATION_RATIO AS AGE_50_64_POPULATION_RATIO,
    D.AGE_65_PLUS_POPULATION_RATIO AS AGE_65_PLUS_POPULATION_RATIO,
    (C.CASES / C.POPULATION) * 100000 AS CASES_PER_100K,
    (C.DEATHS / C.POPULATION) * 100000 AS DEATHS_PER_100K,
    D.FIPS
FROM CALIFORNIA_COVID19_DATASETS.COVID.CASES C
JOIN RAW.CA_COUNTY_DEMOGRAPHICS_2020 D
  ON UPPER(TRIM(C.AREA)) = UPPER(TRIM(D.COUNTY_NAME));


CREATE OR REPLACE TABLE CALIFORNIA_COVID_ANALYTICS.ANALYTICS.CA_CASES_DEMOGRAPHICS_AGG AS
SELECT
    DATE,
    AREA,
    SUM(CASES) AS TOTAL_CASES,
    SUM(DEATHS) AS TOTAL_DEATHS,
    AVG(CASES/POPULATION*100000) AS CASES_PER_100K,
    AVG(DEATHS/POPULATION*100000) AS DEATHS_PER_100K
FROM CALIFORNIA_COVID19_DATASETS.COVID.CASES
GROUP BY DATE, AREA;


CREATE OR REPLACE MATERIALIZED VIEW CALIFORNIA_COVID_ANALYTICS.ANALYTICS.CA_TREND_MV
CLUSTER BY (DATE, AREA) AS
SELECT *
FROM CALIFORNIA_COVID_ANALYTICS.ANALYTICS.CA_CASES_DEMOGRAPHICS_AGG;


ALTER TABLE CALIFORNIA_COVID_ANALYTICS.ANALYTICS.CA_CASES_DEMOGRAPHICS_AGG
CLUSTER BY (DATE, AREA);